[project]
name = "ru-en-nmt"
description = "Russian-English neural machine translator"
version = "0.1.0"
authors = [
  {name = "Maxim Son", email = "son.mp146@gmail.com"},
]
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
    "dvc[gdrive]>=3.67.1",
    "dvc-gdrive>=3.0.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "torch>=2.14.0",
    "scikit-learn>=1.9.1",
    "nltk>=3.10.3",
    "sacremoses>=0.2.0",
]
